version: '3'

networks:
  api_service:

services:
  db:
    image: mysql/mysql-server:8.0.24
    container_name: db
    restart: on-failure
    env_file:
      - ./.env.develop
    networks:
      - api_service
    ports:
      - "3306:3306"
    volumes:
      - tfpersData:/var/lib/mysql

  tfpers-api:
    # build: .
    image: ghcr.io/tfpers/tfpers-service:dev
    container_name: backend
    restart: on-failure
    env_file:
      - ./.env.develop
    depends_on:
      - db
    networks:
      - api_service
volumes:
  tfpersData: