version: '3'

networks:
  name: api_service

services:
  db:
    image: mysql/mysql-server:8.0.24
    container_name: db
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=mydbapp
    networks:
      - api_service
    ports:
      - "3306:3306"
    volumes:
      - tfpersData:/var/lib/mysql

  tfpers-api:
    build: .
    container_name: backend
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_NAME=mydbapp
      - DB_PORT=3306
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - api_service
volumes:
  tfpersData: