version: '3'

networks:
  api_service:

services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    restart: on-failure
    environment:
      - MYSQL_DATABASE=my_db_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    # env_file:
    #   - ./.env.develop
    networks:
      - api_service
    ports:
      - "3307:3306"
    volumes:
      - tfpersDatabase:/var/lib/mysql

  tfpers-api:
    # build: .
    image: ghcr.io/tfpers/tfpers-service:dev
    container_name: backend
    restart: on-failure
    env_file:
      - ./.env.develop
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - api_service
    volumes:
      - ./serviceapi/uploads/:/uploads/
volumes:
  tfpersDatabase: